# Generated by Django 5.2.9 on 2025-12-12 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Titre de la tâche', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Statut de complétion')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
